"""Add university table and relations

Revision ID: 8a950a8d6bfc
Revises: 6337a09f0fc5
Create Date: 2025-06-15 13:13:58.592033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a950a8d6bfc'
down_revision: Union[str, None] = '6337a09f0fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classroom', sa.Column('university_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'classroom', 'university', ['university_id'], ['id'])
    op.add_column('group', sa.Column('university_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group', 'university', ['university_id'], ['id'])
    op.add_column('teacher', sa.Column('university_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher', 'university', ['university_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'university_id')
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'university_id')
    op.drop_constraint(None, 'classroom', type_='foreignkey')
    op.drop_column('classroom', 'university_id')
    # ### end Alembic commands ###
