"""init

Revision ID: eeb212e3137f
Revises: 633743abfd40
Create Date: 2025-05-29 16:29:22.740401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eeb212e3137f'
down_revision: Union[str, None] = '633743abfd40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'TEACHER', 'STUDENT', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'TEACHER', 'STUDENT', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###
